In [1]:
import pandas as pd
import dateutil.relativedelta
import quandl
import sys
import pickle
from sklearn.externals import joblib

In [2]:
quandl.ApiConfig.api_key = "bkLgy-fmbYDf_AuKMJeV"

In [3]:
sp_test = pd.read_csv("GSPC.csv")

In [4]:
column_not_needed = ["Open","High","Low","Adj Close","Volume"]

In [5]:
sp_test.drop(column_not_needed,axis=1,inplace=True)

In [6]:
sp_test.columns = ['datekey','sp_price']

In [7]:
sp_test['datekey'] = pd.to_datetime(sp_test['datekey'])

In [8]:
stck_fund_attr = ['datekey','DE','PE1','PS1','PB','NETMARGIN',
                                        'MARKETCAP',
                                        'EV',
                                        'EVEBITDA',
                                        'REVENUEUSD',
                                        'GP',
                                        'EBITDA',
                                        'NETINCCMNUSD',
                                        'EPSDIL',
                                        'DEBTUSD',
                                        'CURRENTRATIO',
                                        'BVPS',
                                        'NCFO',
                                        'DEPAMOR',
                                        'SBCOMP',
                                        'NCFI',
                                        'CAPEX',
                                        'NCFBUS',
                                        'NCFINV',
                                        'NCFF',
                                        'NCFDEBT',
                                        'NCFCOMMON',
                                        'NCFDIV',
                                        'NCFX',
                                        'NCF',
                                        'SPS',
                                        'PAYOUTRATIO',
                                        'TANGIBLES',
                                        'TBVPS',
                                        'WORKINGCAPITAL',
                                        'price']
cmpny_financials_attr  = stck_fund_attr.copy()

cmpny_financials_attr.extend(['sp_price' ,'price_change' ,'sp_price_change' ,'diff' ,'status'])                                     
                  
cmpny_financials_attr = [x.lower() for x in cmpny_financials_attr]                                                                                   

df_company_fundmntls = pd.DataFrame(columns=stck_fund_attr)

In [9]:
df_company_fundmntls = quandl.get_table('SHARADAR/SF1', qopts={"columns":stck_fund_attr}, ticker=['MMM'],dimension = 'ARQ')

In [10]:
company_ticker = 'MMM'
company_ticker

'MMM'

In [11]:

try:
        
          print("starting " + company_ticker)

          df_company_fundmntls = quandl.get_table('SHARADAR/SF1', qopts={"columns":stck_fund_attr}, ticker=[company_ticker],dimension = 'ARQ')
        
          df_company_fundmntls.fillna(0.0)
    
          df_company_fundmntls = df_company_fundmntls.sort_values(by=['datekey'])
          df_company_fundmntls["sp_price"] = 0.0
          df_company_fundmntls["price_change"] = 0.0
          df_company_fundmntls["sp_price_change"] = 0.0
          df_company_fundmntls["diff"] = 0.0
          df_company_fundmntls["status"] = "underperform"
            

    
          stock_start_value = 0.0
          sp_start_value = 0.0
          diff = 0
        

         
          
          for index,row in df_company_fundmntls.iterrows():
             
              

              try:
                   check_sp_date_exists = sp_test[(sp_test.datekey == row["datekey"])]
                   df_company_fundmntls.set_value(index,"sp_price",check_sp_date_exists["sp_price"])

              except ValueError:
                   rpt_dt = row["datekey"]
                   print(rpt_dt)
                   rpt_dt = rpt_dt - dateutil.relativedelta.relativedelta(days=4)
                   print(rpt_dt)
                   check_sp_date_exists = sp_test[(sp_test.datekey == rpt_dt)]
                   df_company_fundmntls.set_value(index,"sp_price",check_sp_date_exists["sp_price"])
                  

    
            
                    
              if (index != 0):

                  if (stock_start_value > 0):
                      df_company_fundmntls.set_value(index,"price_change",(((row["price"] - stock_start_value) / stock_start_value)*100))

                  if (sp_start_value > 0.0):

                      df_company_fundmntls.set_value(index,"sp_price_change" ,(((check_sp_date_exists["sp_price"] - sp_start_value) / sp_start_value)*100))
                  diff = (df_company_fundmntls.get_value(index,"price_change") - df_company_fundmntls.get_value(index,"sp_price_change"))
                  df_company_fundmntls.set_value(index,"diff", diff)
              else:
                  stock_start_value = row["price"]
                  sp_start_value = df_company_fundmntls.get_value(index,"sp_price")


              if diff > 0:
                    status = "outperform"
              else:
                    status = "underperform"  
            
              df_company_fundmntls.set_value(index,"status", status)   
#               stock_start_value = row["price"]

              

              
              
            
          print("ending" + company_ticker)

except quandl.NotFoundError as e:

        print(company_ticker + " not found ")
        pass
        
except Exception as e :
        print("Unexpected error:", sys.exc_info()[0])
        pass

starting MMM
endingMMM

/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:32: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:58: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:66: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:49: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:53: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:54: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/Users/jijijacob/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:55: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [13]:

X_test = df_company_fundmntls[(df_company_fundmntls.datekey == df_company_fundmntls["datekey"].max())]
X_test = X_test.reset_index()
column_not_needed = ["None","datekey","price","sp_price","price_change",'sp_price_change','diff','status']
X_test.drop(column_not_needed,axis=1,inplace=True)

In [14]:
X_test

,de,pe1,ps1,pb,netmargin,marketcap,ev,evebitda,revenueusd,gp,...,ncfdebt,ncfcommon,ncfdiv,ncfx,ncf,sps,payoutratio,tangibles,tbvps,workingcapital
0,2.28,27.416,4.207,11.479,0.065,132730995000,143626995000,15.816,7990000000,3910000000,...,2193000000,-352000000,-699000000,50000000,222000000,52.982,1.335,24538000000,41.15,6590000000

In [15]:
saved_rf = joblib.load('rand_frst.pkl')

In [16]:
saved_rf.predict(X_test)[0]

'outperform'

In [17]:
df_pred_val = df_company_fundmntls[['datekey','pe1','tangibles','sps','ps1','debtusd','evebitda',
                      'depamor','de','epsdil','price','sp_price','price_change','sp_price_change','status']]

In [21]:
df_pred_val["status"] = saved_rf.predict(X_test)[0]

In [22]:
df_pred_val = df_pred_val.reset_index()

In [23]:
df_pred_val.drop('None',axis=1,inplace=True)

ValueError: labels ['None'] not contained in axis

In [24]:
df_pred_val

,index,datekey,pe1,tangibles,sps,ps1,debtusd,evebitda,depamor,de,epsdil,price,sp_price,price_change,sp_price_change,status
0,0,2008-05-02,15.048,21217000000,35.369,2.221,6182000000,8.701,268000000,1.153,1.38,78.55,1413.900024,0.000000,0.000000,outperform
1,1,2008-08-01,13.261,20590000000,36.441,1.925,6008000000,7.867,285000000,1.183,1.33,70.15,1260.310059,-10.693826,-10.862859,outperform
2,2,2008-10-31,11.952,20773000000,37.334,1.722,7036000000,7.146,293000000,1.263,1.41,64.30,968.750000,-18.141311,-31.483840,outperform
3,3,2009-02-17,9.580,18396000000,36.140,1.312,6718000000,5.887,307000000,1.586,0.78,47.42,789.169983,-39.630808,-44.184881,outperform
4,4,2009-05-01,13.429,17403000000,34.456,1.680,6034000000,7.812,271000000,1.458,0.74,57.88,877.520020,-26.314449,-37.936204,outperform
5,5,2009-07-31,17.284,18975000000,32.829,2.148,6080000000,9.656,298000000,1.377,1.12,70.52,987.479980,-10.222788,-30.159137,outperform
6,6,2009-10-30,18.347,20380000000,32.029,2.297,6125000000,10.165,290000000,1.190,1.35,73.57,1036.189941,-6.339911,-26.714059,outperform
7,7,2010-02-16,17.531,20076000000,33.009,2.422,5710000000,9.999,298000000,1.093,1.31,79.94,1094.869995,1.769574,-22.563832,outperform
8,8,2010-05-05,16.945,21001000000,34.254,2.528,5778000000,9.804,287000000,1.045,1.29,86.59,1165.869995,10.235519,-17.542261,outperform
9,9,2010-08-04,15.827,21608000000,35.541,2.476,5677000000,9.386,272000000,1.019,1.54,88.00,1127.239990,12.030554,-20.274420,outperform
10,10,2010-11-05,15.016,22887000000,36.520,2.364,5758000000,8.934,278000000,0.918,1.53,86.34,1225.849976,9.917250,-13.300095,outperform
11,11,2011-02-16,16.142,21516000000,37.357,2.472,5452000000,9.688,283000000,0.903,1.27,92.33,1336.319946,17.542966,-5.486956,outperform
12,12,2011-05-05,15.980,22004000000,38.826,2.445,5619000000,9.849,289000000,0.863,1.49,94.92,1335.099976,20.840229,-5.573240,outperform
13,13,2011-08-04,13.705,23024000000,40.053,2.053,5600000000,8.358,319000000,0.839,1.60,82.23,1200.069946,4.684914,-15.123423,outperform
14,14,2011-11-03,13.295,23023000000,41.304,1.928,6159000000,8.040,311000000,0.867,1.52,79.64,1261.150024,1.387651,-10.803451,outperform
15,15,2012-02-16,14.488,22653000000,41.794,2.097,5166000000,8.649,317000000,1.022,1.35,87.65,1358.040039,11.584978,-3.950773,outperform
16,16,2012-05-03,14.535,23060000000,42.747,2.091,5174000000,8.691,313000000,0.951,1.59,89.39,1391.569946,13.800127,-1.579325,outperform
17,17,2012-08-02,14.529,24428000000,42.690,2.110,6307000000,8.659,321000000,1.004,1.66,90.08,1365.000000,14.678549,-3.458521,outperform
18,18,2012-11-01,14.077,25416000000,42.722,2.089,6358000000,8.517,322000000,0.926,1.65,89.25,1427.589966,13.621897,0.968240,outperform
19,19,2013-02-14,16.059,24566000000,43.096,2.385,6001000000,9.562,332000000,0.901,1.41,102.78,1521.380005,30.846595,7.601668,outperform
20,20,2013-05-02,16.517,24942000000,43.484,2.439,5936000000,9.798,336000000,0.857,1.61,106.04,1597.589966,34.996817,12.991721,outperform
21,21,2013-08-01,18.273,25113000000,43.984,2.692,5946000000,10.805,335000000,0.884,1.71,118.41,1706.869995,50.744749,20.720699,outperform
22,22,2013-10-31,19.039,24517000000,45.144,2.788,5777000000,11.226,343000000,0.863,1.78,125.85,1756.540039,60.216423,24.233681,outperform
23,23,2014-02-13,19.054,24517000000,45.272,2.875,6009000000,11.186,357000000,0.891,1.62,130.14,1829.829956,65.677912,29.417209,outperform
24,24,2014-05-01,20.030,24559000000,46.966,2.998,6577000000,11.946,350000000,0.895,1.79,140.81,1883.680054,79.261617,33.225831,outperform
25,25,2014-07-31,19.487,24945000000,48.236,2.921,6973000000,11.618,358000000,0.929,1.91,140.89,1930.670044,79.363463,36.549262,outperform
26,26,2014-10-30,20.444,24047000000,49.079,3.099,7344000000,12.178,350000000,1.025,1.98,152.10,1994.650024,93.634628,41.074333,outperform
27,27,2015-02-12,21.744,22784000000,49.016,3.385,6837000000,12.919,350000000,1.383,1.82,165.91,2088.479980,111.215786,47.710584,outperform
28,28,2015-04-30,20.337,22313000000,49.620,3.152,6591000000,12.167,339000000,1.199,1.85,156.39,2085.510010,99.096117,47.500529,outperform
29,29,2015-07-30,19.407,23048000000,49.295,3.075,8517000000,11.751,344000000,1.394,2.02,151.57,2108.629883,92.959898,49.135713,outperform
30,30,2015-10-29,20.001,21272000000,49.460,3.187,11253000000,12.530,355000000,1.726,2.05,157.61,2089.409912,100.649268,47.776355,outperform
31,31,2016-02-11,19.517,20868000000,48.392,3.114,10797000000,11.925,397000000,1.791,1.66,150.67,1829.079956,91.814131,29.364165,outperform
32,32,2016-05-03,21.155,21056000000,49.564,3.389,11139000000,13.179,356000000,1.808,2.05,167.97,2063.370117,113.838320,45.934655,outperform
33,33,2016-08-02,22.267,21402000000,49.565,3.599,11749000000,13.829,366000000,1.791,2.08,178.36,2157.030029,127.065563,52.558879,outperform
34,34,2016-11-01,20.228,22199000000,49.765,3.301,12361000000,12.708,368000000,1.833,2.15,164.25,2111.719971,109.102482,49.354264,outperform
35,35,2017-02-09,21.339,21420000000,49.792,3.579,11650000000,13.246,384000000,2.191,1.88,178.18,2307.870117,126.836410,63.227249,outperform
36,36,2017-05-03,23.361,21765000000,50.803,3.890,11711000000,14.515,438000000,2.025,2.16,197.63,2388.129883,151.597708,68.903730,outperform
37,37,2017-08-01,22.626,22651000000,51.050,3.980,11301000000,14.234,380000000,1.925,2.58,203.18,2476.350098,158.663272,75.143225,outperform
38,38,2017-10-31,25.103,23841000000,51.867,4.438,11663000000,15.734,377000000,1.897,2.33,230.19,2575.260010,193.049013,82.138763,outperform
39,39,2018-02-08,27.416,24538000000,52.982,4.207,13949000000,15.816,349000000,2.280,0.85,222.89,2581.000000,183.755570,82.544731,outperform